var num1 = prompt('Digite um número: ')
var num2 = prompt('Digite outro número: ')

document.write('A soma entre ' + num1 + ' e ' + num2 + ' é: ' + (parseInt(num1) + parseInt(num2)) + '<br>')
document.write('A subtração entre ' + num1 + ' e ' + num2 + ' é: ' + (parseInt(num1) - parseInt(num2)) + '<br>')
document.write('A múltiplicação entre ' + num1 + ' e ' + num2 + ' é: ' + (parseInt(num1) * parseInt(num2)) + '<br>')
document.write('A divisão entre ' + num1 + ' e ' + num2 + ' é: ' + (parseInt(num1) / parseInt(num2)) + '<br>')
document.write('O módulo entre ' + num1 + ' e ' + num2 + ' é: ' + (parseInt(num1) % parseInt(num2)) + '<br>')
document.write('<hr><p>Incremento e decremento</p><hr>')
document.write('O Pré incremento de ' + num1 + ' é: ' + (++num1) + '<br>')
document.write('O Pós incremento de ' + num1 + ' é: ' + (num1++) + '<br>')
document.write(num1 + '<br>')
document.write('O Pré decremento de ' + num1 + ' é: ' + (--num1) + '<br>')
document.write('O Pós decremento de ' + num1 + ' é: ' + (num1--) + '<br>')
document.write(num1)